$(function(){
    $(".hamburguer").click(function(){
        $(".menu").toggleClass("active");
    });
    $(".see-more").click(function(){
        $(".more").show();
        $(this).hide();
    });
});